### ISSUE TITLE
No such file "smplx_faces.npy" and IndexError: list index out of range when Execute

### ISSUE THREAD

**Issue by muximuxi** [kwan3854/CEB_ECON#10]
Thank you for your great work, when I did following CEB Econ Tutorial, when "Exucute"  , the error message is as follows, how to solve it ？
File "F:\Econ-texture\ECON_39_env\lib\site-packages\numpy\lib\npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\AppData\\Roaming\\Blender Foundation\\Blender\\3.6\\scripts\\addons\\CEB_ECON\\ECON\\lib\\dataset\\../../data/smpl_related\\smpl_data/smplx_faces.npy'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\CEB_ECON\econ_blender.py", line 560, in execute
    bpy.ops.wm.obj_import(filepath=final_obj[-1]) #import o ultimo
IndexError: list index out of range
Error: Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\CEB_ECON\econ_blender.py", line 560, in execute
    bpy.ops.wm.obj_import(filepath=final_obj[-1]) #import o ultimo
IndexError: list index out of range

**Comment by muximuxi** [comment]
DOwnloads all models file will fix this
